server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: abbtech-bookstore-api-gw
  main:
    banner-mode: off
  cloud:
    gateway:
      mvc:
        routes:
          - id: abbtech-bookstore-inventory-ms
            uri: http://127.0.0.1:8082
            predicates:
              - Path=/api/books/**
            filters:
              - RewritePath=/api/books/(?<segment>.*), /abbtech-bookstore-inventory-ms/$\{segment}

          - id: abbtech-bookstore-notification-ms
            uri: http://127.0.0.1:8084
            predicates:
              - Path=/api/notifications/**
            filters:
              - RewritePath=/api/notifications/(?<segment>.*), /abbtech-bookstore-notification-ms/$\{segment}

          - id: abbtech-bookstore-order-ms
            uri: http://127.0.0.1:8083
            predicates:
              - Path=/api/orders/**
            filters:
              - RewritePath=/api/orders/(?<segment>.*), /abbtech-bookstore-order-ms/$\{segment}
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
